export const ScribendCopy = {
  APP_NAME: 'Scribend',
  TAGLINE_PRIVACY: 'Your privacy.',
  TAGLINE_DEVICE: 'Your device.',
  TAGLINE_PATIENTS: 'Your patients.',
  OFFLINE_BADGE: '100% On-Device',
  CONTINUE: 'Continue',
  OPEN_SETTINGS: 'Open Settings',

  PERMISSIONS_TITLE: 'Local Permissions',
  PERMISSIONS_DESC: 'Scribend needs local permissions to work offline. Demo mode can continue without simulator permissions.',
  MICROPHONE_ACCESS: 'Microphone Access',
  MICROPHONE_DESC: 'Record visit audio locally on this device.',
  LOCAL_STORAGE_ACCESS: 'Local Storage Access',
  LOCAL_STORAGE_DESC: 'Save visits and notes in local app storage.',
  REQUIRED: 'Required',
  GRANTED: 'Granted',
  DENIED: 'Denied',
  PERMISSION_ERROR: 'Scribend needs microphone and local storage access to record and save visits locally.',

  OFFLINE_MODE_ACTIVE: 'Offline Mode Active',
  OFFLINE_MODE_DESC: 'All data stays on this device.',
  START_VISIT: 'Start Visit',
  PATIENT_HISTORY: 'Patient History',
  LOCAL_FOOTER: 'All data saved on this device.',

  SELECT_PATIENT_TYPE: 'Select Patient Type',
  SELECT_PATIENT_TYPE_DESC: 'Choose the patient category to continue.',
  MALE: 'Male',
  FEMALE: 'Female',
  SELECT_PATIENT: 'Select Patient',
  SEARCH_PATIENTS: 'Search patients',
  ADD_NEW_PATIENT: '+ Add New Patient',
  NO_PATIENTS: 'No patients found',
  NO_MATCHING_PATIENTS: 'No matching patients found',
  INVALID_PATIENT: 'Selected patient is missing.',
  LAST_VISIT: 'Last visit',

  FULL_NAME: 'Full Name',
  AGE: 'Age',
  GENDER: 'Gender',
  PRIMARY_CONDITION: 'Primary Condition',
  CURRENT_MEDICATIONS: 'Current Medications',
  ALLERGIES: 'Allergies',
  SAVE_PATIENT: 'Save Patient',
  NAME_REQUIRED: 'Name required',
  AGE_INVALID: 'Age must be valid',
  GENDER_REQUIRED: 'Gender required',
  NEW_PATIENT: 'New patient',
  NOT_SPECIFIED: 'Not specified',
  NONE_LISTED: 'None listed',
  NO_KNOWN_ALLERGIES: 'No known drug allergies',

  VISIT_IN_PROGRESS: 'Visit in Progress',
  RECORDING: 'Recording',
  TRANSCRIBING: 'Transcribing',
  EXTRACTING_HISTORY: 'Extracting History',
  GENERATING_NOTE: 'Generating Note',
  COMPLETE: 'Complete',
  START_RECORDING: 'Start Recording',
  STOP_RECORDING: 'Stop Recording',
  CANCEL_VISIT: 'Cancel Visit',
  DISCARD_VISIT: 'Discard this visit?',
  KEEP_VISIT: 'Keep Visit',
  RECORDING_TOO_SHORT: 'Recording too short. Please record a longer visit.',
  RETRY: 'Retry',
  TRANSCRIPT_EMPTY: 'Transcript was empty. Please retry.',
  SOAP_GENERATION_FAILED: 'SOAP note generation failed.',

  SOAP_NOTE: 'SOAP Note',
  SUBJECTIVE: 'Subjective',
  OBJECTIVE: 'Objective',
  ASSESSMENT: 'Assessment',
  PLAN: 'Plan',
  RETRIEVED_PATIENT_CONTEXT: 'Retrieved Patient Context',
  REVIEW_BAR: 'Review • Edit • Confirm',
  SAVE_NOTE_LOCALLY: 'Save Note Locally',
  EDIT_NOTE: 'Edit Note',
  START_NEW_VISIT: 'Start New Visit',
  VIEW_NOTE: 'View Note',
  NO_NOTE_GENERATED: 'No note generated',
  ALREADY_SAVED: 'Already saved locally',
  SAVE_FAILED: 'Save failed. Please retry.',
  READ_ONLY: 'Read-only saved note',

  SAVED_SUCCESS_TITLE: 'Note Saved Successfully!',
  SAVED_SUCCESS_DESC: 'Your note has been saved securely on this device.',
  NO_SAVED_NOTES: 'No saved notes yet.',
  SAVED_NOTE_NOT_FOUND: 'Saved note was not found.',
  NO_ASSESSMENT: 'No assessment available',
  NO_LOCAL_CONTEXT: 'No local context retrieved.',
  DEMO_ENCOUNTER_DESC: 'Begin a synthetic local demo encounter.',
  LOCAL_ONLY_TITLE: 'Local-only AI bridge',
  LOCAL_ONLY_DESC: 'Current AI behavior is mocked in TypeScript and can later route to native ExecuTorch.',
  BACK: 'Back',
};
