export const routes = {
  Welcome: 'Welcome',
  Permissions: 'Permissions',
  Home: 'Home',
  HomeTabs: 'HomeTabs',
  HomeDashboard: 'HomeDashboard',
  Patients: 'Patients',
  PatientType: 'PatientType',
  SelectPatient: 'SelectPatient',
  AddNewPatient: 'AddNewPatient',
  PatientDetail: 'PatientDetail',
  VisitInProgress: 'VisitInProgress',
  SoapNote: 'SoapNote',
  Saved: 'Saved',
  PatientHistory: 'PatientHistory',
  Notes: 'Notes',
  Profile: 'Profile',
} as const;
